spring:
  # 启用的配置文件环境
  profiles:
    active: dev
  application:
    name: similarity-backend
  # redis
  redis:
    port: ${similarity.redis.port}
    database: ${similarity.redis.database}
    host: ${similarity.redis.host}
    password: ${similarity.redis.password}
  # MySQL
  datasource:
    driver-class-name: ${similarity.datasource.driver-class-name}
    username: ${similarity.datasource.username}
    password: ${similarity.datasource.password}
    url: ${similarity.datasource.url}
  # session 失效时间（分钟）
  session:
    timeout: 86400
    store-type: redis
  # 配置日期格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
server:
  port: 8080
  servlet:
    context-path: /api
    session:
      cookie:
        domain:

#mybatis-plus
mybatis-plus:
  configuration:
    mapUnderscoreToCamelCase: false
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
# swagegr + knife4j
knife4j:
  enable: true
  openapi:
    title: similarity
    description: "similarity接口文档"
    group:
      test1:
        group-name: group1
        api-rule: package
        api-rule-resources:
          - cn.edu.dlmu.backend.controller

# 七牛云配置
qiniu:
  accessKey: ${similarity.qiniu.accessKey}
  secretKey: ${similarity.qiniu.secretKey}
  bucketName: ${similarity.qiniu.bucketName}
  domain: ${similarity.qiniu.domain}

